### ISSUE TITLE
ImportError: No module named coltools

### ISSUE THREAD

**Issue by dylib** [coljac/progmon#1]
Hello,

Could you please tell me where I could locate the `coltools` module? Thank you!

**Comment by coljac** [comment]
That import was unneeded - I removed it. Pull the latest version and give it a go.

I'll commit some more changes in the next day or so as well.

**Comment by dylib** [comment]
I noticed another [repo](https://github.com/coljac/ansify) of yours which is also using `coltools` (https://github.com/coljac/ansify) — I'm really interested in checking that one out, but same issue I guess. 

Thank you!

**Comment by coljac** [comment]
The module is where I keep all my personal convenience functions; I should be more careful to either remove it or just put it into github. Thanks for the notification there, will fix.
